### ISSUE TITLE
Issue: Unterticket erstellen

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#100]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [ ] T88 Ein Unterticket benötigt (fast) die selben wie ein Oberticket
- [ ] T89 Manche Angaben können von Oberticket abweichen (siehe Ph).
- [ ] T92 Ein Unterticket erbt manche Angaben von Oberticket (siehe Ph).

**Comment by Luk-T** [comment]
(Notiz an mich, damit ich nicht immer im PH nachschauen muss)

Vererbt wird:
Visibility Status, Priorität, Liste von Vorgängern

**Comment by marlonschlosshauer** [comment]
@Luk-T Hey hey die Aufgaben könnte man in der Tracebility noch abhacken, oder?

**Comment by Luk-T** [comment]
Erledigt 👍
