### ISSUE TITLE
Issue: Rest

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#102]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T32 Nur Kunde und Projektleiter kann Ticket abbrechen
- [x] T33 Nur Kunde und Projektleiter kann Ticket in Verhandlungs oder Bearbeitungsphase abbrechen
- [x] T34 Nur Projektleiter kann Ticket in Abschlussphase bewegen
- [x] T35 Nur Projektleiter kann Ticket zu Status "Abgeschlossen" bewegen wenn der Status "Review" erreicht ist
- [x] T36 Nur Projektleiter kann Status zu "Archiviert" ändern
- [x] T50 Ein "Fehler" Ticket startet automatisch in "Bearbeitungsphase"
- [x] T55 Die Zeitschätzung eines Tickets darf nicht weniger als Zeitschätzung aller Untertickets sein
- [x] T74 Falls Verhandlungsphase übersprungen wurde kann geschätzter Aufwand eingetragen werden
- [x] T75 Nur Mitarbeiter mit "Schreib" kann Aufwand eintragen falls Verhandlung übersprungen
- [x] T78 Ist Ticket in Abschlussphase, können keine Zeiten mehr gebucht oder bearbeitet werden
- [x] T80 Wenn Status "Abgebrochen" erreicht wird Status von allen Untertickets zu abgebrochen geändert
- [x] T85 Status "Review" kann nur betreten werden wenn alle Untertickets abgeschlossen sind

**Comment by pheim1** [comment]
T32&33 schneidet sich mit M29.0: Während der Bearbeitungsphase kann der Kunde das Ticket abbrechen

**Comment by marlonschlosshauer** [comment]
Hab es angepasst, danke 👍

**Comment by pheim1** [comment]
T32 & T33 & T78 (Ausgenommen Projektleiter&Company, die dürfen weiterhin) wurde durch #58 implementiert.
