### ISSUE TITLE
IssueTimeSheet: Enddatum kann mit PUT nicht hinzugefügt werden

### ISSUE THREAD

**Issue by sfuerder** [gedankenessen/goose-backend#106]
**Beschreibung des Bugs**
Bei den meisten Issues kann ich mit einem PUT die timeSheets nicht ändern.
Bekomme immer folgende Fehlermeldung.

<img width="1492" alt="Bildschirmfoto 2021-05-21 um 13 29 21" src="https://user-images.githubusercontent.com/37979892/119130462-92dfaf80-ba38-11eb-9511-0f31582af463.png">

Etwas seltsam ist, dass es bei manchen issues geht, aber ich noch nicht wirklich herausgefunden habe, woran das liegt

**Branches**
- Frontend: feature/TimeService
- Backend: master

**Comment by pheim1** [comment]
Ist ein Bug, der mir in #105 aufgefallen ist, sollte mit dem PR gelöst sein.

**Comment by pheim1** [comment]
@sfuerder könntest du bitte überprüfen, ob der Fehler gefixed wurde?

**Comment by sfuerder** [comment]
Funktioniert jetzt 👍🏼
