### ISSUE TITLE
Achieved Status kann nicht geändert werden

### ISSUE THREAD

**Issue by sfuerder** [gedankenessen/goose-backend#108]
Beim Ändern des Requirements bekomme ich folgenden Fehler.

<img width="1492" alt="Bildschirmfoto 2021-05-24 um 12 23 06" src="https://user-images.githubusercontent.com/37979892/119334084-f7924880-bc8a-11eb-98df-0614e5c4b32d.png">

Ich bin mir nicht ganz sicher aber theoretisch kann ich den achieved Status erst ändern, sobald eine Zusammenfassung erstellt wurde oder? Vorher wird ja noch nicht mit dem abarbeiten angefangen.

**Comment by pheim1** [comment]
Ok, ja hab gerade nochmal im Code nachgeschaut, da muss ich das dann nochmal anpassen, da bei einem Update ein pre check das updaten eines Requirements bei schon vorhandenere Zusammenfassung blockiert ist. 

Werde dir nachher ein Hotfix erstellen.

**Comment by pheim1** [comment]
Hotfix dürfe Online sein: https://github.com/gedankenessen/goose-backend/releases/tag/v0.1.4

Bitte überprüfe es nochmal.

**Comment by sfuerder** [comment]
Funktioniert jetzt ebenfalls 👍🏼
