### ISSUE TITLE
Testing im Backend

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#11]
@pheim1 hat mich darauf aufmerksam gemacht, dass wir gerade keine Test Strategie haben. Mein Kopf sagt mir, dass wir jetzt schon damit anfangen könnten. Philipp, hättest du einen Beispiel für einen Test ?  

 @gedankenessen/backend habt ihr dazu irgendwelche Fragen ?

**Comment by pheim1** [comment]
#46 beinhaltet Unit & Integrationstests, soweit wie ich gesehen habe, sind in #48 auch Integrationstests vorhanden an denen man sich Orientiren kann.
