### ISSUE TITLE
Endpunkt für alle Issues eines Users

### ISSUE THREAD

**Issue by Yochyo** [gedankenessen/goose-backend#112]
Wir brauchen einen Endpunkt der alle Issues zurückgibt, deren ein User zugeteilt ist. Siehe M13. Ich würde mich darum kümmern sobald die Vorgänger/Unterticket Geschichte fertig ist.

**Comment by Yochyo** [comment]
@BenjaminKuerten sollen alle Issues eines Projekts denen der User zugewiesen ist oder wirklich ALLE Issues denen er zugewiesen ist zurückgegeben werden?

**Comment by marlonschlosshauer** [comment]
@sfuerder @mschwer1 Habt ihr den Endpunkt auch angefragt (für das abfragen ob Timer schon wo gestartet wurde) ?

**Comment by Yochyo** [comment]
der Endpunkt ist noch in keinem Release. Er wird mit #114 in das Projekt gemerged.

**Comment by marlonschlosshauer** [comment]
Yo yo. Wir haben noch ein Problem mit dem erhalten der Timesheets, das dem nahe liegt. Aber ich fände eine Lösung über den Timesheet Endpunkt passender 🚀

**Comment by sfuerder** [comment]
> @sfuerder @mschwer1 Habt ihr den Endpunkt auch angefragt (für das abfragen ob Timer schon wo gestartet wurde) ?

Das war die ursprüngliche Idee. Habe jetzt aber schon mitbekommen, dass das backend seidig gelöst wurde
