### ISSUE TITLE
GetAllIssueChildren: Abfragen von Untertickets der Untertickets

### ISSUE THREAD

**Issue by BenjaminKuerten** [gedankenessen/goose-backend#113]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

Damit wir das Backend nicht mit Anfragen bombardieren benötigen wir einen Endpunkt der uns alle Untertickets zurückgibt, heißt auch die Untertickets der Untertickets. Diese können theoretisch ohne Relation zurückgegeben werden (als einfache Liste).

**Comment by pheim1** [comment]
Was mich mal interessieren würde, hast du es mal mit dem "Anfragen bombardieren" versucht? Bzw. ob sich das bei der Menge überhaupt auf die Laufzeit auswirkt. 

Ansonsten wäre es ja ein optionales feature, welches wir ans Ende der aktuellen Arbeitstakten packen, oder @marlonschlosshauer ?

**Comment by BenjaminKuerten** [comment]
Ich habe schon mit @Yochyo gesprochen, die Funktion ist schon fast implementiert, wobei es für das Frontend eine menge Arbeit wäre. Bei 3 Untertickets müssten wir 16 Anfragen schicken, bei 4 Untertickets müssten wir schon 64 Anfragen senden.

**Comment by pheim1** [comment]
Alles klar, hätte mich mal interessiert wie sich das auf die Performance auswirkt, auf langer Sicht natürlich schrecklich, aber im Rahmen des Projektes meinte ich...
