### ISSUE TITLE
Issue: Baustelle

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#120]
- [x] #118 GetParent wirft 404
- [x] Bug: Es kann der gleiche Vorgänger 2 mal hinzugefügt werden.
- [x] Bug: issues blockieren nicht automatisch wenn ein Unterticket/Vorgänger hinzugefügt wird
- [ ] Bug: Wenn man ein Oberticket im Unterticket als Vorgänger setzt, bekommt man einen BadRequest (400), aber es wird dennoch als Vorgänger gesetzt

**Branches**
- Frontend: SubTickets
- Backend: master

**Comment by marlonschlosshauer** [comment]
@Yochyo Du hattest gemeint den letzten Bug hier ("Oberticket im Unterticket als Vorgänger") konntest du nicht machen. War das nur Momentan oder gibt es da größere Probleme?

**Comment by Yochyo** [comment]
@BenjaminKuerten meinte der Vorgänger wird gesetzt, man bekommt aber den falschen Statuscode zurück. Entweder der Bug wurde nicht gefixt oder tritt nur unter bestimmten Vorraussetzungen auf.

**Comment by marlonschlosshauer** [comment]
Sollten wir den Bug dann nicht fixen? Wir können aber das Ticket auch schließen, den Fehler genauer überprüfen und mit einem vollen Bug Report rangehen.

**Comment by Yochyo** [comment]
Bis jetzt konnte ich ihn nicht reproduzieren. Ich habe das Issue offen gelassen falls der Fehler nochmal auftritt.

**Comment by marlonschlosshauer** [comment]
Gut, ich würde das schließen und auf einen größeren Report warten. So ist es für alle einfacher zu verstehen was schon als Bug eingetragen ist und was noch unbekannt ist.
