### ISSUE TITLE
Issues sollen erst in den ReviewStatus können wenn alle Untertickets abgeschlossen sind.

### ISSUE THREAD

**Issue by Yochyo** [gedankenessen/goose-backend#121]
Momentan ist es so, dass ein Unterticket blockiert wird, so lange ein Unterticket noch nicht abgeschlossen ist.

Zukünftigt sollte es aber so sein, dass ein Unterticket das Oberticket nicht blockiert. Das Oberticket aber erst in den ReviewStatus gesetzt werden kann wenn alle Untertickets abgeschlossen sind.

@gedankenessen/frontend

**Comment by marlonschlosshauer** [comment]
Danke für die Dokumentation 👍 Ich weiße dich mal dem Issue zu, das klar ist wer was machen muss 🐶

**Comment by Yochyo** [comment]
@gedankenessen/frontend

**Comment by Yochyo** [comment]
Bitte schließt das Issue wenn bei euch alles funktioniert
