### ISSUE TITLE
Ticket im Status Review in die Abschlussphase setzen, durch einen CustomState

### ISSUE THREAD

**Issue by Namo2** [gedankenessen/goose-backend#123]
**Beschreibung des Bugs**
Wenn ein Ticket in der Bearbeitungsphase ist und man einen Custom State (Abschlussphase) setzen möchte (siehe ST54),
dann folgt der folgende Error.
```json
{
"message":"cannot update an issue state from Review to Custom  Abschluss",
"status":400,
"type":"HttpStatusException",
"stackTrace":""
}
```
CompanyId: 60bce2f64f524d084725b0e8
ProjectId: 60bce3444f524d084725b0eb

Getestet als Firma/Projektleiter (STests/SMitarbeiter)

**Reproduktions Schritte**
1. Ticket erstellen.
2. Ticket den Status 'Review' geben.
3. Einen eigenen Status in der Abschlussphase erstellen.
4. In den Ticketeinstellungen den neuen Status setzen.

**Erwartetes Verhalten**
Der Status wird gesetzt und das Ticket kommt in die Abschlussphase.

**Branches**
- Frontend: main
- Backend: master

**Comment by marlonschlosshauer** [comment]
Ist das ``customState`` auch Issue baustelle @Yochyo

**Comment by Yochyo** [comment]
Es gab noch kein Release mit custom states. Sollte gleich gehen.

**Comment by Yochyo** [comment]
@Namo2 kann das issue geschlossen werden?

**Comment by Namo2** [comment]
Ich teste das die Tage nochmal und schließe dann das Ticket.
Danke für die Erinnerung :+1:
