### ISSUE TITLE
Startdatum kann nicht in Bearbeitungsstatus gesetzt werden

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#124]
Ist da Logik dahinter um den Vorgänger/Unter/Ober/Ticket Algo in die Luft zu jagen?

**PUT Startdatum**
![PUT Startdatum](https://user-images.githubusercontent.com/24259317/121181133-f9026a00-c861-11eb-8d06-716a504279cc.png)

**GET Ticket**
![GET Ticket](https://user-images.githubusercontent.com/24259317/121181142-fa339700-c861-11eb-93bc-7ead1dc03016.png)

**Reproduktions Schritte**
1. Erstelle Ticket als Fehler (startet automatisch in Bearbeiten)
2. Füge Startdatum zu Ticket hinzu
3. PUT 200 OK
4. Startdatum ist nicht da

**Ids**
Issue: 60bf59ed4f524d084725b19f
Project: 60bf4e864f524d084725b185
Company: 609421f4d837b069802b738e
User: 609421f4d837b069802b738d

**Branches**
- Frontend: main
- Backend: master

**Comment by Yochyo** [comment]
Das sollte umsetztbar sein. Ich schaue es mir an

**Comment by Yochyo** [comment]
Man kann jetzt das StartDatum in der Bearbeitungsphase verändern (außer man ist im ReviewState) wenn die Verhandlungsphase übersprungen wurde.

**Comment by marlonschlosshauer** [comment]
Top 👍 Hau es Live wenn du Zeit hast.

**Comment by Yochyo** [comment]
@gedankenessen/frontend

**Comment by Yochyo** [comment]
Bitte schließt das Issue wenn bei euch alles funktioniert
