### ISSUE TITLE
Fehlermeldungen

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#125]
Wir brauchen noch alle Fehlermeldungen für das [Pflichtenheft](https://docs.google.com/document/d/1sEfx8s7TNK57mixii6nnmde-BA_Cg0rQ6gjhfIwLcpw/edit#). Gäbe es da einen einfachen weg die alle zu erhalten?

**Comment by Yochyo** [comment]
Momentan sind alle Fehlermeldungen an der jeweiligen Stelle im Codehargecoded. Eventuell sollten wir einer Datei speichern, sodass wir nur auf diese Zugreifen müssen.

**Comment by marlonschlosshauer** [comment]
> Momentan sind alle Fehlermeldungen an der jeweiligen Stelle im Codehargecoded. Eventuell sollten wir einer Datei speichern, sodass wir nur auf diese Zugreifen müssen.

Das hätten wir vor einem Monat machen sollen 😂 Haben die ein Keyword oder werden die von einer Funktion aufgerufen das man danach suchen kann?

**Comment by Yochyo** [comment]
Es gibt einige Kriterien wonach man suchen kann, sollte also machbar sein. Müssen die Fehlermeldungen eigentlich deutsch sein?

**Comment by marlonschlosshauer** [comment]
> Es gibt einige Kriterien wonach man suchen kann, sollte also machbar sein.

Super. Wissen die anderen auch davon? Dann könnten wir das sammeln Verteilen (falls jeder Zeit hat). 

> Müssen die Fehlermeldungen eigentlich deutsch sein?
Ne, aber selbst wenn würde ich es jetzt nicht mehr ändern.

**Comment by Madara789** [comment]
ja gut man kann auch einfach in Visual Studio nach HttpStatusException suchen und sich alle anzeigen lassen dann hat man alle Fehlermeldungen.

**Comment by marlonschlosshauer** [comment]
> ja gut man kann auch einfach in Visual Studio nach HttpStatusException suchen und sich alle anzeigen lassen dann hat man alle Fehlermeldungen.

Das war mit "ein Keyword oder werden die von einer Funktion aufgerufen" gemeint 🌚 

138 Fehlermeldungen. Aua.

**Comment by marlonschlosshauer** [comment]
Hab die Fehlermeldungen mal hier eingefügt: [Errors](https://docs.google.com/spreadsheets/d/1KC9pcwWCDbQPDAdCCh0eltcluTPUFacd9z_tp9np6dQ/edit#gid=1087085455)

Sind nicht genau 138 weil ich ein paar Zeilen doppelt gezählt hatte. Es ist zwar kein Kontext von den Fehlermeldungen da, aber ihr könnt gerne die Texte anpassen. Bin aber auch so zufrieden.
