### ISSUE TITLE
Zusammenfassung kann nicht in Unterticket angenommen werden

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#128]
![Screen Shot 2021-06-15 at 17 23 08](https://user-images.githubusercontent.com/24259317/122080174-5bc5a980-cdfe-11eb-8757-317c0ee8f697.png)

**Daten**
Oberticket ist Blockiert und hat Zusammenfassung angenommen:
URL: http://localhost:4200/609421f4d837b069802b738e/projects/60c8bcd7bc60a864d3bcf4ab/issues/60c8c42bbc60a864d3bcf4dd
Ticket: 60c8c42bbc60a864d3bcf4dd
Oberticket: 60c8bcecbc60a864d3bcf4b5
Projekt: 60c8bcd7bc60a864d3bcf4ab
Firma: 609421f4d837b069802b738e

Oberticket ist in "Überprüfung" *(?)* und hat nicht Zusammenfassung angenommen:
URL: http://localhost:4200/609421f4d837b069802b738e/projects/60c8bcd7bc60a864d3bcf4ab/issues/60c8c660bc60a864d3bcf4eb
Ticket: 60c8c660bc60a864d3bcf4eb
Oberticket: 60c8c646bc60a864d3bcf4ea
Projekt: 60c8bcd7bc60a864d3bcf4ab
Firma: 609421f4d837b069802b738e

**Fehlermeldung**
```json
{"message":"Object reference not set to an instance of an object.","status":500,"type":"NullReferenceException","stackTrace":""}
```

**Reproduktions Schritte**
1.  Oberticket erstellen (Blockiert, Zusammenfassung angenommen, zwei andere Untertickets)
2. Erstelle Unterticket (als Feature)
3. Setze Status in Untertickert zu Verhandlung
4. Erstelle Zusammenfassung
5. Autor kann Zusammenfassung nicht annehmen

**Branches**
- Frontend: main
- Backend: master

**Comment by Yochyo** [comment]
Ich kann den Bug nicht reproduzieren. Ich habe als Firma die Zusammenfassung des Untertickets erstellt und akzeptiert. Habe ich irgendetwas anders als bei dir gemacht?

**Comment by marlonschlosshauer** [comment]
Ich schaue es mir nochmal an und melde mich 👍

**Comment by marlonschlosshauer** [comment]
Hab es mit neuem Ober&Unter-Ticket probiert und konnte die Zusammenfassung nicht annehmen.

URL: http://ticketgoose.de/609421f4d837b069802b738e/projects/60bf6649d76b6d225409a63c/issues/60c8f8653f7bf23add138d61

Nutzer: CWetzel & MSchlosshauer

Fehlermeldung:
```json
{"message":"Object reference not set to an instance of an object.","status":500,"type":"NullReferenceException","stackTrace":""}
```


Bei einem anderen Ticket hatte ich auch das Problem das ich nicht die Zusammenfassung annehmen konnte (ohne Oberticket). Ich schätze mal da geistert irgendwo etwas herum. 


@Madara789 Hättest du Zeit da reinzuschauen?

**Comment by Madara789** [comment]
sollte mit dem nächsten Release gelöst sein!
