### ISSUE TITLE
Kunde keine Berechtigung Zusammenfassung anzunehmen

### ISSUE THREAD

**Issue by WhiroWhat** [gedankenessen/goose-backend#130]
**Beschreibung des Bugs**
Kunde kann die Zusammenfassung nicht anzunehmen oder ablehnen.

**Reproduktions Schritte**
1. Neues Projekt erstellt (mit kunde x)
2. Ticket erstellt
3. Requirements hinzugefügt und Zusammenfassung erstellt
4. Kunde kann nicht akzeptieren
![image](https://user-images.githubusercontent.com/48799541/122086756-49e70500-ce04-11eb-8764-c6435f6dda71.png)

**Erwartetes Verhalten**
Zusammenfassung sollte man annehmen können

**Branches**
- Frontend: main
- Backend: master

**Comment by Yochyo** [comment]
Momentan kann nur der Kunde die Zusammenfassung annehmen, wenn er das Issue erstellt hat. Ansonsten können nur Firma und projektleiter die Zusammenfassung annehmen. @Madara789 soll das so sein?

**Comment by WhiroWhat** [comment]
@Yochyo Es soll ziemlich sicher nicht so sein. https://github.com/gedankenessen/goose-frontend/issues/189

**Comment by Madara789** [comment]
also damals ich das implementiert hatte hieß es das der Kunde eine Zusammenfassung nur annehmen kann wenn er das Ticket auch erstellt hat.

**Comment by Madara789** [comment]
mit dem nächsten Release wird der Kunde auch berechtigt sein die Zusammenfassung anzunehmen!
