### ISSUE TITLE
Falsche Conversation, wenn Ticket durch Hinzufügen eines Vorhänger blockiert wird 

### ISSUE THREAD

**Issue by Luk-T** [gedankenessen/goose-backend#131]
Es steht immer "Status wurde von Blockiert in Blockiert gewechselt." auch wenn es davor nicht blockiert war

**Comment by Luk-T** [comment]
Ich kann einfach die Stelle nicht finden, wo diese Nachricht generiert wird

**Comment by Yochyo** [comment]
Kannst du beschreiben, was genau du getan hast?

**Comment by Luk-T** [comment]
Ich habe gerade versucht, die Nachricht in einem neuen Projekt zu reproduzieren, aber das hat nicht geklappt. Da krieg ich keine Nachrichten mehr, das sich der Status verändert hat. Sehr seltsam.

Ich denke, wenn der Fehler nicht reproduzierbar ist, würde ich das Issue direkt wieder zumachen.
