### ISSUE TITLE
Untertickets werden nicht abgebrochen, wenn man das Oberticket abbricht

### ISSUE THREAD

**Issue by Luk-T** [gedankenessen/goose-backend#132]
st 92
m 43.5

**Comment by marlonschlosshauer** [comment]
Das hat vor zwei Wochen noch funktioniert. Ich kann mich daran erinnern das wir das EN gezeigt haben. Hm hm.

**Comment by Luk-T** [comment]
Ich hab die TIckets abgebrochen, indem ich den Status manuell auf abgebrochen gesetzt habe. Vielleicht kann man Tickets noch irgendwie anders abbrechen, und es funktioniert nur dort.

**Comment by Luk-T** [comment]
Ich hab das auch nochmal getestet, weil der andere Fehler auch nur in einem alten Projekt auftrat.

Hab ein neues Projekt angelegt und es hat dort einwandfrei geklappt. Wahrscheinlich war das alte Projekt einfach nur irgendwie broken :/
