### ISSUE TITLE
Kann von eigenem Status (Verhandlungsphase) zu Bearbeiten (ohne Zusammenfassung zu akzeptieren)

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#135]
**Beschreibung des Bugs**
Die Zusammenfassung kann übersprungen werden wenn ein eigener Status für die Verhandlungsphase erstellt wurde, und dieser ausgewählt wird.

![image](https://user-images.githubusercontent.com/24259317/122106950-d6042700-ce1a-11eb-8b7b-a66a839f3466.png)

**Reproduktions Schritte**
1. Erstelle neuen Status: z.B. "Analyse", in Verhandlungsphase
2. Erstelle neues Ticket mit "Feature" 
3. Ändere Ticket Status von "Überprüfen" zu "Analyse"
5. Ändere Ticket Status von "Analyse" zu "Bearbeiten"
5. Ticket befindet sich jetzt in "Bearbeiten", ohne Zusammenfassung akzeptiert zu haben

**Erwartetes Verhalten**
Beim wechsel zu "Bearbeiten" sollte eine Fehlermeldung erscheinen. 

**Branches**
- Frontend: main
- Backend: master

**Comment by Yochyo** [comment]
Man kann auch im Status Verhandlung den Status auf Bearbeitung ändern. Wird gefixt

**Comment by marlonschlosshauer** [comment]
yoyo gabs dafür schon einen fix?
