### ISSUE TITLE
Kunde kann kein Unterticket erstellen

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#144]
**Beschreibung des Bugs**
Wollte von einem Ticket (Bearbeitung) ein Unterticket als Kunde erstellen.

![image](https://user-images.githubusercontent.com/24259317/123552021-93c0db00-d774-11eb-9ab7-9370e3912885.png)

Das Ticket wurde nun zwei mal erstellt (?):
![image](https://user-images.githubusercontent.com/24259317/123552053-b05d1300-d774-11eb-9b5c-845c0e525087.png)
(Siehe Ticket "test")

Habe ein zweites mal es Versucht und es wurde nur ein Unterticket erstellt (AAA -> BBB)
![image](https://user-images.githubusercontent.com/24259317/123552112-f3b78180-d774-11eb-93b3-4585042d0c08.png)

**Reproduktions Schritte**
1. Erstelle Oberticket als Firma
2. Erstelle Zusammenfassung & nehme sie an
3. Wechsele Account zu Kunde
4. Versuche Unterticket von Oberticket zu erstellen

**Branches**
- Frontend: main
- Backend: master

**Comment by Yochyo** [comment]
Bugfix ist raus. Wird im nächsten Release gefixt sein.
