### ISSUE TITLE
Kann nicht von "Review" zu "Bearbeiten" (oder eigenen Statusen)

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#145]
![image](https://user-images.githubusercontent.com/24259317/123552793-11d2b100-d778-11eb-930a-c6fdfeeff27c.png)

**Branches**
- Frontend: main
- Backend: master

**Comment by Yochyo** [comment]
Man soll aus dem Reviewstatus ein Issue nur abbrechen oder abschließen können (oder in einen eigenen Status in der Abschließphase). Zumindest war es so im Statusdiagramm vorgesehen.

**Comment by marlonschlosshauer** [comment]
Hm, macht wenig Sinn. Wie viel Arbeit wäre es wenn du es so machst, das man auch wieder zurück in die anderen Statuse kann?

**Comment by Yochyo** [comment]
Das ist nicht viel arbeit. Aber warum soll ein Issue von der Reviewphase wieder in die Bearbeitungsphase gehen können?

**Comment by marlonschlosshauer** [comment]
Also ich meine Review Status und Bearbeiten Status. "Review" dient als Check ob das Ticket abgeschlossen ist oder ob noch etwas fehlt.
Mein Gedankengang ist; Was bringt ein Review wenn ich nur abrechnen oder abschließen kann? Vielleicht wurde ein Problem gefunden welches noch gefixed werden muss.

**Comment by Yochyo** [comment]
Okay, das macht Sinn. Ich schreibe einen Bugfix der dann ebenfalls mit dem nächsten Release oben ist.

**Comment by Yochyo** [comment]
Bug ist gefixt, getestet und gepusht.
