### ISSUE TITLE
Unterticket blockiert nicht bei Vorgänger von Oberticket

### ISSUE THREAD

**Issue by WhiroWhat** [gedankenessen/goose-backend#148]
**Beschreibung des Bugs**
Wenn ein Ticket einen Vorgänger hat kann man nicht in die Bearbeitungsphase gehen (es blockiert stattdessen).
Das Unterticket sollte auch blockieren wenn das Oberticket einen Vorgänger hat, tut es aber nicht.

**Reproduktions Schritte**
1. "Oberticket erstellen"
2. "Unterticket" vom Oberticket erstellen
3. Vorgänger zum Oberticket hinzufügen
4. Oberticket Zusammenfassung machen und abschicken -> Status "Blockiert"
5. Unterticket Zusammenfassung machen und abschicken -> Status "Bearbeiten"

**Erwartetes Verhalten**
Das Unterticket sollte auch Blockieren

**Branches**
- Frontend: main
- Backend: master

**Comment by Yochyo** [comment]
Ein Unterticket soll nicht blockieren. Allerdings kann ein Oberticket erst in den Reviewstatus wenn alle Untertickets angeschlossen sind.
