### ISSUE TITLE
Datenbank-Transaktionen / Sessions

### ISSUE THREAD

**Issue by Luk-T** [gedankenessen/goose-backend#21]
Wie können wir Datenbank-Transaktionen am besten in unserer Architektur umsetzen? Ich denke das wir zumindest für das Überprüfen von Deadlocks beim hinzufügen von Nachfolgern nicht darum kommen werden.

Code-Beispiel:
https://developer.mongodb.com/how-to/transactions-c-dotnet/

**Comment by pheim1** [comment]
Mit dem Connection String in Discord kann man nun Sessions verwenden.
