### ISSUE TITLE
Project Business Logik

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#30]
Autorisierung
- [x] Nur Firmenaccount kann Projekte erstellen
- [ ] Nur Firmenaccount kann Projektrollen Verteilen
- [ ] Nur Mitarbeiter können eigene Status erstellen, bearbeiten und entfernen

Logik
- [x] Beim Erstellen eines Projekts auch die Standardstatus anlegen
- [x] Nur ein Projektleiter pro Projekt
- [x] Ein Status kann nur gelöscht werden, wenn sich kein Ticket in dem Status befindet
- [x] Die Standardstatus können nicht gelöscht werden

**Comment by Luk-T** [comment]
Ich erlaube mir mal dieses Ticket zu schließen, weil die restlichen Punkte in [56](https://github.com/gedankenessen/goose-backend/issues/56) abgearbeitet werden.
