### ISSUE TITLE
Authentifizierung

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#32]
- [x] Authentication-Controller
 - [x] SignIn-Endpunkt um einen JWT-Token zu bekommen
 - [x] JWT-Konfiguration (Lifetime, Claims)
 - [x] Autorisierungs Attribut

**Comment by pheim1** [comment]
Den Authentifizierungs-Teil dürfte soweit fertig sein, was jedoch noch etwas Zeit benötigt, ist das Autorisierungs-Attribut (#9). Morgen habe ich mir vorgenommen daran weiter zu entwickeln.

**Comment by pheim1** [comment]
Ich habe heute einiges ausprobiert und mich genauer mit der asp.net Dokumentation auseinander gesetzt was Authentifizierung angeht. Ich werde voraussichtlich morgen (falls ich zeit finde) und den Montag noch brauchen, bis ich einen geeigneten Kandidat für ein PR habe.

**Comment by marlonschlosshauer** [comment]
Kein Problem, nimm ruhig den langen weg. Mittwoch wäre so meine Deadline. Wir bräuchten das bisher für #30 und #43.

**Comment by pheim1** [comment]
So, ich hab gerade ein PR gestartet. Inhalt wie schon hier beschrieben, das Registrieren (unserer Kunden = Firma) und Login.

Des weiteren wollte ich eigentlich das Rollen-Attribut hinzufügen, da ich es schon mal in einem Demo Projekt implementiert hatte. Problem ist nur, das wir die URLs gekürzt haben und deswegen es nicht einfach möglich war den Code der schon existierte so zu übernehmen. 

Ich habe mich deswegen für einen neuen Ansatz für das Thema Autorisierung entschieden, Stichpunkt Imperative Autorisierung.
Vorteile: 
* Nicht nur in Controller-Klassen/Endpunkten kann nun autorisiert werden, sondern auch in Services usw.
* Widerverwendbarkeit von Requirements/Handlers
* Gut realisierbar ohne bestehenden Routen anpassen zu müssen
* "state of the art" im Gegensatz zu dem Attributen Ansatz

Um Imperative Autorisierung zu verstehen muss man drei punkte verstehen.
1. _Requirements_: sind vorgaben, die ein _Handler_ überprüfen muss. Praktisch eine Klasse mit Properties, die überprüft werden müssen.
2. _Handlers_: Sind Routinen, die ein oder mehrere _requirements_ überprüfen.
3. Mehrere _handlers_ können ein _requirement_ überprüfen.

Bsp.:  ProjectService.cs: CreateProjectAsync-Method: Zeile 51.

 [Dokumentation von MS](https://docs.microsoft.com/de-de/aspnet/core/security/authorization)

**Comment by marlonschlosshauer** [comment]
Wenn #46 gemerged ist, werden dann für Requests im Frontend und mit Swagger Credentials benötigt ?

**Comment by pheim1** [comment]
> Wenn #46 gemerged ist, werden dann für Requests im Frontend und mit Swagger Credentials benötigt ?

Nein, die sind weiterhin erstmal offen (sonst würde es ja alles ausbremsen).
