### ISSUE TITLE
Issue Endpunkt: Erstellung, Typisierung und Status

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#41]
[Aufgaben](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=0):
- [x] T7 Mitarbeiter können Tickets erstellen
- [x] T13 Ticket wird mit Status "Überprüfung" (in Verhandlungphase) gestartet
- [x] T48 Ein Ticket hat einen Typ
- [x] T49 Ein Ticket kann von Typ "Fehler" oder "Feature" sein
- [x] T52 Ein Ticket kann erstellt werden wenn es die benötigten Eigenschaften hat (siehe Pflichtenheft)
- [x] T53 Ein Ticket kann bearbeitet werden
- [x] T54 Nur bestimmte Eigenschaften eines Tickets können immer bearbeitet werden (siehe Ph.)
- [x] Tests

**Comment by marlonschlosshauer** [comment]
Wurde das schon gemerged?

**Comment by Yochyo** [comment]
Wurde gemerged.
