### ISSUE TITLE
IssueConversation

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#43]
Hast du schon ein paar Kriterien gefunden ? ([link](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=0)) 

Autorisierung:
- [x] T24 Nur Benutzer die mindst. Schreibrecht haben können Nachrichten versenden
- [x] T27: Nur Benutzer die mindst. Leserecht (auf Ticket) haben können Nachrichten lesen

Logik:
- [x] T25: Falls Status Archiviert kann keine Nachricht erstellt werden
- [x] T56: Der Kommunikationsverlauf eines Tickest beinhaltet verschiedene Elemente (siehe Ph.)
- [x] Nachrichten
- [x] Statuswechsel
- [x] Zusammenfassungen
- [x] Unterticket hinzugefügt/entfernt
- [x] Vorgänger  hinzugefügt/entfernt

**Comment by Luk-T** [comment]
Ich hab mal alle Punkte zu dem Thema aus der Traceability map und dem PH zusammengetragen.
Zwei Punkte will nochmal ansprechen, ich hab sie auch in der Traceability map kommentiert:
T24 und T40 sind aus meiner sicht das gleiche
T35 stimmt nicht ganz mit dem PH überein

**Comment by marlonschlosshauer** [comment]
>     * [ ]  **_T24 / T40_**: Nur Benutzer die mindst. Schreibrecht haben können Nachrichten versenden
>     * [ ]  T27: Nur Benutzer die mindst. Leserecht (auf Ticket) haben können Nachrichten lesen

Ich frage morgen Philipp mal nach dem Status von Auth. Wenn er meint es bräuchte noch mehr Zeit, würde ich diese Kriterien verschieben.

> 
>     * [ ]  T25: Falls **_Phase Abschlussphase / Status Archiviert (?)_** kann keine Nachricht erstellt werden


Hab den Text hier angepasst. Ist jetzt über Status Archiviert. Wäre auch so im Arbeitspaket drin 👍 
 
>     * [ ]  T56: Der Kommunikationsverlauf eines Tickest beinhaltet verschiedene Elemente (siehe Ph.)

Ebenfalls gutes Kriterium für das AP.


> T24 und T40 sind aus meiner sicht das gleiche

Hmm, yo. Hab T40 mal gelöscht 👍 

> T35 stimmt nicht ganz mit dem PH überein

Hab den Text zu ``Nur Projektleiter kann Ticket zu Status "Abgeschlossen" bewegen wenn der Status "Review" erreicht ist``  geändert. Also statt "Abschlussphase" steht jetzt "Status Abgeschlossen". Kommt das dem Kriterium näher ?


Fazit: Kann so starten 🦒 
Schreibe deinen Namen bei der Tracebility hin und füge ein "N" hinzu bei dem das du bearbeiten wirst.

**Comment by Luk-T** [comment]
> Hab den Text zu Nur Projektleiter kann Ticket zu Status "Abgeschlossen" bewegen wenn der Status "Review" erreicht ist geändert. Also statt "Abschlussphase" steht jetzt "Status Abgeschlossen". Kommt das dem Kriterium näher ?

Oh sorry, das war ein Tippfehler, ich hab eigentlich T25 statt T35 gemeint 😄 

Hab die Punkten unter Logik in der Traceability map eingetragen, bei den Punkten unter Autorisierung mal noch nicht.

**Comment by Luk-T** [comment]
Kurzes Update: Ich hab alle Punkte unter Logik fertig, mit Ausnahme von den Nachrichten die bei den Zusammenfassungen erstellt werden sollen. Da würde ich erstmal warten, bis der Pull Request https://github.com/gedankenessen/goose-backend/pull/55/files fertig ist.

Bei zwei Punkten war ich mir unsicher:
- Soll das Feld CreatorUserId auch bei vom System automatisch generierten Nachrichten ausgefüllt werden?
Bei einer z.B. Statusänderung könnte man da den Nutzer eintragen, der den Status geändert hat - Oder wird null bevorzugt, weil der Nutzer die Nachricht nicht im eigentlichen Sinne geschrieben hat?
- Wie genau soll Data bei diesen Nachrichten aussehen?
Ich das bisher wie folgt implementiert: Ich hätte bei den Unterticket- und Vorgängernachrichten nur die Id des anderen Tickets eingetragen, und dann das Frontend eine sinnvolle Nachricht daraus erzeugen lassen. Durch die Id könnte dann direkt das andere Ticket verlinkt werden.
Bei Statusänderungen hab ich in Data hingegen direkt den Text reingeschrieben der auch im Frontend angezeigt wird - Hier will man wahrscheinlich nicht verlinken, und ein Status könnte auch gelöscht werden. wodurch eine Id ungültig werden würde.

**Comment by marlonschlosshauer** [comment]
> Soll das Feld CreatorUserId auch bei vom System automatisch generierten Nachrichten ausgefüllt werden?

Ich hab nicht jedenfall im Kopf aber für die Statusänderung wäre das aufjedenfall gut.

> Wie genau soll Data bei den automatischen Nachrichten aussehen?

Ich würde das Backend das handeln lassen. Nur eine Id zu senden (wie du es sicherlich auch in Verteilte Systeme machst) wäre korrekter, aber die Frontend Leute haben noch genug zu tun.
