### ISSUE TITLE
GET Issue und GET Issues wirft 500 (ohne und mit "all" Flag)

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#44]
Bin über Swagger drauf gekommen. **Habe davor falsche GET Requests (leere oder falsche projectId und issueId) an GET Issue über Angular gesendet.** Zuvor hab ich in Angular einen 404 bekommen, jetzt bekomme ich dort auch den Fehlercode 500. 
GET Companies funktioniert noch in Swagger & Angular.

### Repo (für momentanes Problem)
1. [Swagger](http://51.254.157.180:5000/swagger/index.html) öffnen
2. GET Issues (mit projectId: 605b80dee61730565bfe4b79)
3. Fehler wird geworfen

Fehle wird auch geworfen wenn ich ``getAll``auf ``true``mache.

#### Request

<http://51.254.157.180:5000/api/projects/605b80dee61730565bfe4b79/issues>

### curl

    curl -X GET "http://51.254.157.180:5000/api/projects/605b80dee61730565bfe4b79/issues" -H  "accept: text/plain"

### Response

    {
      "message": "Object reference not set to an instance of an object.",
      "status": 500,
      "type": "NullReferenceException"
    }

**Comment by Yochyo** [comment]
Ich schreibe nach und nach die ganzen Unit Tests für die Issue Endpunkte. Im nächsten Commit wird das hier gefixt sein.

**Comment by sfuerder** [comment]
Wann funktioniert der Issue Endpunkt richtig auf dem live System?

**Comment by Yochyo** [comment]
Es scheint als wäre der Datensatz in der Datenbank fehlerhaft. Es wäre glaube ich gut, wenn alle wir einmal die ganze Datenbank, oder zumindest alle Issues, löschen.

@pheim1 bekomme ich von dir davon das Okay?

**Comment by Yochyo** [comment]
Issue collection wurde gecleart
