### ISSUE TITLE
Brauchen wir für die Zusammenfassung in der Verhandlungsphase ein weiteres Flag in IssueDetail

### ISSUE THREAD

**Issue by Yochyo** [gedankenessen/goose-backend#45]
Im Pflichtenheft steht, "Wenn eine Zusammenfassung erstellt wurde, dürfen keine Requirements mehr hinzugefügt werden bis die Zusammenfassung akzeptiert oder abgelehnt wurde".

In IssueDetail haben wir das Flag "RequirementsAccepted" das prüft, ob die Zusammenfassung akzeptiert wurde. Allerdings fehlt eine Flag mit dem überprüft werden kann ob mom. eine Zusammenfassung existiert die noch akzeptiert werden muss. Müssen wir das Datenbankschema erweitern?

**Comment by pheim1** [comment]
> Wenn eine Zusammenfassung erstellt wurde, dürfen keine Requirements mehr hinzugefügt werden bis die Zusammenfassung 
> akzeptiert oder abgelehnt wurde

RequirementsAccepted = false; Verhandlungsphase = true; **requirements = empty array;**

> Allerdings fehlt eine Flag mit dem überprüft werden kann ob mom. eine Zusammenfassung existiert die noch akzeptiert werden muss

RequirementsAccepted = false; Verhandlungsphase = true;  **requirements = non empty array;**

requirements = zusammenfassung
Oder hab ich da was falsch verstanden? Kannst mich gerne korrigieren 😁

**Comment by Yochyo** [comment]
Ich war der Auffassung, dass Requirements nach und nach hinzugefügt werden.

Wenn ich das bei dir richtig verstehe, würde man durch das erstellen von Requirements die Zusammenfassung erstellen.

Wenn "nicht leeres array" "zusammenfassung wurde erstellt" entspricht, bräuchte man noch einen Endpunkt, bei dem man mehrere Requirements gleichzeitig erstellen kann. Sonst würden alle Erstellversuche nach dem ersten blockiert werden.

**Comment by pheim1** [comment]
Ok, dann benötigen wir, falls keinem was anderes einfällt ein weiteres Feld in der DB (Model-Klasse anpassen).

**Comment by Yochyo** [comment]
@Luk-T @Madara789

**Comment by pheim1** [comment]
Ich glaube, dass ich es, als ich die DB designend habe mit dem Status abfragen wollte. 
Pflichtenheft: M38.0 ->"Requirements hinzufügen, entfernen"/"Zusammenfassung schicken" habe das als eigener Status aufgefasst. Aber es gibt solche Status ja nicht. Ich glaube nachträglich ein Status einzuführen wäre zu aufwendig, deswegen ist die Flag Idee nicht so schlecht.

**Comment by Yochyo** [comment]
Dann würde ich eine Variable namens "RequirementsSummaryCreated" dafür in IssueDetails erstellen. Das Model im Frontend (@gedankenessen/frontend) müsste allerdings angepasst werden. 

Muss die Datenbank eventuell auch neu aufgesetzt werden oder ist der Wert einfach false (false ist der default Wert von bool) wenn das Feld in der DB fehlt?

**Comment by pheim1** [comment]
> Muss die Datenbank eventuell auch neu aufgesetzt werden oder ist der Wert einfach false (false ist der default Wert von bool) wenn das Feld in der DB fehlt?

Prinzipiell würde man eine Migration schreib, der jedem Dokument der Collection, dieses Feld hinzufügt, aber da wir ja nicht wirklich viel Daten haben, kann man es per CLI-Befehl/UpdateMany(...) hinzufügen. Kannst auch gerne mal versuchen, was passiert wenn du einfach nur das Feld bei einem hinzufügst und bei einem anderen nicht.

**Comment by Madara789** [comment]
Issue kann geschossen werden oder ? hab das mit dem neusten PR eingebaut.
