### ISSUE TITLE
Error-500 beim registrieren von User mit selbem Username

### ISSUE THREAD

**Issue by BenjaminKuerten** [gedankenessen/goose-backend#47]
**Beschreibung des Bugs**
Beim registrieren von einem Nutzer der bereits existiert vom Username wird ein Error 500 geworfen. 

**Reproduktions Schritte**
1. Nutzer Max Mustermann anmelden
2. Registrierung erfolgreich
3. Nutzer Max Mustermann anmelden
4. Error 500

**Erwartetes Verhalten**
Nutzer MMustermann2 wird als Username erstellt

**Comment by Madara789** [comment]
Ich konnte den Fehler nicht wirklich reproduzieren.
Daraufhin bin ich mit Louis kurz den Fehler durchgegangen und hier war die Sache das der Firmenname Unique sein muss und als wir den Firmennamen geändert hatten konnten wir einen User mit einen gleichen Namen erstellen.
Warum nun so eine Fehlermeldung angezeigt wird ist mir noch nicht ganz bewusst, ich bin das eben in Swagger durchgegangen und habe dort die richtige Fehlermeldung bekommen.

Auf welcher Branch habt ihr das genau getestet?

**Comment by BenjaminKuerten** [comment]
Der Fehler kam von Luis und wurde nur von mir in ein Issue gepackt. 
Sollte ein Firmenname vergeben sein, sollte eher ein BadRequest zurückkommt mit einer Fehlermeldung, sodass das für einen Nutzer auch ersichtlich ist bzw. für uns auch unterscheidbar. Andernfalls würde auch das System vom Username Sinn machen, wobei ich eine Fehlermeldung auch für vollkommen ausreichend halte.

**Comment by pheim1** [comment]
Bitte Branch angeben. Habt ihr das mit der aktuellen Live Version gemacht oder im #46?

**Comment by marlonschlosshauer** [comment]
@BenjaminKuerten Was hatte sich hier geändert das du es geschlossen hast ?
