### ISSUE TITLE
Wie greift man auf den mongo docker zu

### ISSUE THREAD

**Issue by Yochyo** [gedankenessen/goose-backend#50]
Die Frage tritt ggf. nochmal in der Zukunft auf, weshalb ich hierfür ein Ticket erstelle.

Ich versuche gerade die Issue collection in der mongo Datenbank zu löschen.
Ich kann aber weder die Datenbank (mit "show dbs") finden noch auswählen.

Ich vermute, dass man sich erst authentifizieren muss, allerdings gingen die im Docker ENV hinterlegten Anmeldedaten nicht.

Zum Nachbilden:
1) Den mongo db docker öffnen
2) eine bash öffnen
3) Den Befehl "mongo" eingeben
4) Alle Datenbanken mit "show dbs" ausgeben

Habe ich etwas falsch gemacht?

**Comment by Yochyo** [comment]
@pheim1

**Comment by Yochyo** [comment]
Worst case setze ich den Docker neu auf.

**Comment by pheim1** [comment]
Wichtig ist immer dass du dich in der DB "admin" mit deinen Credentials anmeldest.

**Comment by Yochyo** [comment]
Bei dieser Datenbank? http://51.254.157.180:9000/#!/1/docker/containers

**Comment by pheim1** [comment]
> Bei dieser Datenbank? http://51.254.157.180:9000/#!/1/docker/containers

Genau, das ist ja unsere Live-Datenbank. Die URL zeigt jedoch auf die Portainer instanz. Unsere Datenbank läuft under 51.254.157.180:27888 (default Port wäre 27017, aber wir haben Port 27888 !)

**Comment by pheim1** [comment]
> Den Befehl "mongo" eingeben

Falls du es in Portainer machst, musst du dich natürlich davor noch mit dem richtigem Benutzername+Passwort anmelden.

`$ mongo --username <username> --password`

**Comment by Yochyo** [comment]
Danke, hab die collection gecleart.
