### ISSUE TITLE
Project: Autorisierung

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#56]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

Dann noch:
- [x] T106 Projekt benötigt einen Kunden um erstellt zu werden
- [x] T10 Nur Firma kann Projekte erstellen

Und von #30 
- [x] Nur Firmenaccount kann Projektrollen Verteilen
- [x] T82 Nur Mitarbeiter (schreibend) und Projektleiter können eigene Status erstellen, bearbeiten und entfernen

Falls dir noch was unter dem Thema "Nur Y darf etwas mit Projekt machen" einfällt kannst du die gerne ergänzen. 
Lukas wäre da dein Ansprechpartner bei Fragen. Falls das zu wenig ist könnten wir mal schauen ob wir die Projektleiter Aufgaben oder Benachrichtigungen anfangen.

**Comment by pheim1** [comment]
@marlonschlosshauer Ich habe eine frage zu `T106 Projekt benötigt einen Kunden um erstellt zu werden`:

Das verwalten von Usern eines Projektes (oder einer Firma) wird über den `/api/projects/{projectId}/users/{userId}` Endpunkt gemacht. Da wir aber schon bei der Erstellung eines Projektes den Kunden setzten müssen, würde es nicht in die vorhandene Architektur passen. 

Ich würde empfehlen, diese Art von Business Logik dem Client (Frontend) überlassen, damit das Backend so variabel wie möglich bleibt.

**Comment by marlonschlosshauer** [comment]
Meinst du mit "diese Art von Business Logik" das ein Kunde gesetzt sein muss ? Ich könnte also über Swagger ein Projekt ohne Kunden erstellen ?

**Comment by pheim1** [comment]
Damit meine ich, dass wir das Backend nicht zubauen sollten. Ablauf wäre dann wie folgt: 

1. Frontend erstellt Projekt über `POST /api/companies/{companyId}/projects`
2. Frontend erstellt Kunden für das erstellte Projekt über `POST /api/projects/{projectId}/users`

**Comment by marlonschlosshauer** [comment]
Kann das Frontend machen 👍  
@Namo2 Das bräuchten wir dann noch in ProjectSettings.

**Comment by Namo2** [comment]
Daran arbeite ich gerade.
Die Logik wollte ich selbst so einbauen :+1:

**Comment by pheim1** [comment]
Nach Rücksprache und nachdem ich mir swagger angeschaut habe, wird nun wie folgt ein Projekt + Kunde Angelegt.

1. Kunde wird für die Firma erstellt. `POST /api/companies/{companyId}/users` **(Dieser Schritt ist nur notwendig, falls es diesen User noch nicht gibt.)**
2. Projekt wird anlegen. `POST /api/companies/{companyId}/projects`
3. Kunde dem Projekt hinzufügen `PUT /api/projects/{projectId}/users/{userId}`

JSON Beispiel Payloads:

**1**  `POST /api/companies/{companyId}/users`
```json
{
  "firstname": "Test",
  "lastname": "Kunde",
  "password": "string1234",
  "roles": [
    {
      "id": "605cc95dd37ccd8527c2ead7"
    }
  ]
}
```

**2** `POST /api/companies/{companyId}/projects`
```json
{
  "name": "Mein Projekt"
}
```

**3** `PUT /api/projects/{projectId}/users/{userId}`
```json
{
  "user": {
    "id": "607c29fbdb7f02ed5fd6ae80"
  },
  "roles": [
    {
      "id": "605cc95dd37ccd8527c2ead7"
    }
  ]
}
```

**Comment by marlonschlosshauer** [comment]
Ich bin immer noch kein Freund von dem PUT beim hinzufügen des Kundens (erstellt aber ist "Änderung") aber so wie du es hier beschreibst, hatte ich es mir auch vorgestellt.

**Comment by pheim1** [comment]
> Ich bin immer noch kein Freund von dem PUT beim hinzufügen des Kundens (erstellt aber ist "Änderung") aber so wie du es hier beschreibst, hatte ich es mir auch vorgestellt.

[PUT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT#responses) steht in HTTP für erstellen und ersetzen wenn vorhanden (idempotent).

**Comment by marlonschlosshauer** [comment]
Da hast ja recht. Ich glaube was mich stört ist das wir nirgends sonst diese Logik verwenden. Aber das liegt einfach daran das es sonst nirgends reinpasst.
