### ISSUE TITLE
Issue: Verhalten Verhandlungsphase

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#57]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T57 Mitarbeiter können einem Ticket zugewiesen werden
- [x] T62 Während Verhandlungsphase hat Kunde nur Zugriff auf bestimmte Funktionen (siehe Ph.)
- [x] T63 Während Verhandlungsphase hat Mitarbeiter nur Zugriff auf bestimmte Funktionen (siehe Ph.)
- [x] T86 Status "Verhandlung" kann nur verlassen werden Zusammenfassung angenommen ist

**Comment by marlonschlosshauer** [comment]
Hey hey, gibt es hierfür eine Timeline? Hatte einen Fehler in der Planung und deswegen werden wir einen Konflikt mit #58 bekommen. Entschuldigung dafür. 

Deadline für mich wäre spätestens Mittwoch (merge inkl.), meinst das ist realistisch?

**Comment by Yochyo** [comment]
Mittwoch ist realistisch. Ich werde vermutlich morgen den PR machen.

**Comment by marlonschlosshauer** [comment]
Super, melde dich bei Philipp wenn der PR durch ist 👍
