### ISSUE TITLE
Issue State ändern

### ISSUE THREAD

**Issue by Madara789** [gedankenessen/goose-backend#60]
Ich muss den Status ändern, momentan kann ich dafür nur einen PUT verwenden und muss bei diesem Request alles mitschicken.
```js
{
  "id": "string",
  "state": {
    "id": "string",
    "name": "string",
    "phase": "string"
  },
  "project": {
    "id": "string",
    "name": "string"
  },
  "client": {
    "id": "string",
    "username": "string",
    "firstname": "string",
    "lastname": "string"
  },
  "author": {
    "id": "string",
    "username": "string",
    "firstname": "string",
    "lastname": "string"
  },
  "issueDetail": {
    "name": "string",
    "type": "string",
    "startDate": "2021-04-18T19:09:45.431Z",
    "endDate": "2021-04-18T19:09:45.431Z",
    "expectedTime": 0,
    "progress": 0,
    "description": "string",
    "requirements": [
      {
        "id": "string",
        "requirement": "string"
      }
    ],
    "requirementsAccepted": true,
    "requirementsSummaryCreated": true,
    "requirementsNeeded": true,
    "priority": 0,
    "visibility": true,
    "relevantDocuments": [
      "string"
    ]
  }
}
```
Irgendwie scheint mir das komisch. Gibts da ne alternative?

**Comment by Madara789** [comment]
@gedankenessen/backend

**Comment by Yochyo** [comment]
Mir ist kein anderer weg bekommt als der folgende:
1) Hol dir alle states vom Projekt
2) Such dir den aus der die richtige Phase/Status hat
3) mach eine PUT Request oder ruf die update methode im Service auf

**Comment by pheim1** [comment]
Abgesehen von @Yochyo Vorschlag, würden nur zwei varianten in fragen kommen, 
bei denen man etwas programmieren müsste <img src="https://user-images.githubusercontent.com/58334704/115227424-bdc0a600-a110-11eb-8b40-ba36a31cd528.png" width="35" height="35">

1. Sub ressource (mit eigenem Controller): .../issues/{issueId}/state
2. [JSON Patch](https://docs.microsoft.com/de-de/aspnet/core/web-api/jsonpatch?view=aspnetcore-5.0) per PATCH-Methode

**Comment by Madara789** [comment]
Ich weiß nicht tatsächlich würde ich dann die Sub resource besser finden.
Mit json patch bin ich nicht vertraut dewegen kann ich dazu nichts sagen.
Aber gut ich würde mich auch damit zufrieden geben, das so zu lassen ich finds halt nur ein bisschen unsinnig den ganzen kram mitzuschicken wenn man nur den State ändern möchte

**Comment by pheim1** [comment]
> ... ich finds halt nur ein bisschen unsinnig den ganzen kram mitzuschicken wenn man nur den State ändern möchte

Genau deswegen gibt es ja JSON Patch.

**Comment by marlonschlosshauer** [comment]
>     3\. ruf die update methode im Service auf

Hat das auch das Problem das man alle Daten mit geben müsste ?

**Comment by Madara789** [comment]
Ich habe das jz so gelassen, dass man den status ändert in dem man ein Put im issue Controller machen
