### ISSUE TITLE
500 bei Issue Requirement

### ISSUE THREAD

**Issue by sfuerder** [gedankenessen/goose-backend#61]
**Beschreibung des Bugs**
Sobald ich ein Requirement erstellen möchte bekomme ich eine 500 Fehlermeldung, das Requirement wird jedoch richtig angelegt.

**Reproduktions Schritte**
1. POST Request erstellen
2. IssueId: 60797813db7f02ed5fd6ae79
3. body:
```js
{
  "requirement": "Requirement 2"
}
```

**Erwartetes Verhalten**
Keine Fehlermeldung zu bekommen, sondern eine 200er Meldung

**Branches**
- Frontend: IssueComponentVS2
- Backend: master

**Comment by Yochyo** [comment]
Fixed, release sollte demnächst oben sein.

**Comment by pheim1** [comment]
Wie ist der Status, wurde es gefixed @sfuerder ?

**Comment by sfuerder** [comment]
Ja wurde behoben
