### ISSUE TITLE
Project State: User Generated

### ISSUE THREAD

**Issue by Namo2** [gedankenessen/goose-backend#62]
Hey,

wollte mich eben daran setzen die UserGenerated States im Frontend anzuzeigen.
Ich hab gemerkt, dass dieser bool bei einem GET nicht mitgeschickt wird.
Wurde das nur vergessen oder gibt es für mich eine andere möglichkeit herauszufinden ob es sich um einen Custom State handelt?

@gedankenessen/backend

**Comment by Yochyo** [comment]
Ich release einen hotfix der gleich oben sein sollte

**Comment by Namo2** [comment]
Nice perfekt.

Kannst du mir noch sagen wie das erstellen eines neuen States dann abläuft?

**Comment by Yochyo** [comment]
Beim erstellen wird UserGenerated automatisch auf true gesetzt. Den Wert musst du also nicht übergeben.
