### ISSUE TITLE
Keine Rolle in Projekt nachdem es erstellt wurde

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#65]
**Beschreibung des Bugs**
Wenn ich ein Projekt erstelle, wird der Benutzer der dieses erstellt nicht zu ProjectUser hinzugefügt. 

**Reproduktions Schritte**
Frontend Schritte:
1. Gehe zu Projekt Dashboard
2. Erstelle Projekt
3. Öffne Projekt
4. Öffne ein Ticket
5. Versucht ProjectUser Endpunkt zu lesen (um Rolle zu erhalten), kriege 404

**Branches**
- Frontend: navigation
- Backend: live

Was meint ihr ist das beste Verhalten hier ? Wir benötigen die Rolle des Benutzers im Projekt im Frontend.

**Comment by pheim1** [comment]
Ich würde ihn bei der Erstellung des Projektes als Mitarbeiter dem Projekt hinzufügen. Da ich bei #56 an der stelle unterwegs bin, kann ich das in das Issue aufnehmen und implementieren. Falls es eilig ist, könnte ich auch ein Hotfix machen...

**Comment by pheim1** [comment]
Damit wir einheitlich wären, müsste man es analog wie hier machen: https://github.com/gedankenessen/goose-backend/issues/56#issuecomment-821992220

**Comment by pheim1** [comment]
Falls es dem Frontend aber helfen würde, kann man es auch einfach dazu implementieren, dass der Ersteller = Company Owner, dem Projekt als Member hinzugefügt wird. Was sagen die anderen dazu?

**Comment by marlonschlosshauer** [comment]
> Damit wir einheitlich wären, müsste man es analog wie hier machen: [#56 (comment)](https://github.com/gedankenessen/goose-backend/issues/56#issuecomment-821992220)

Ich wusste doch das wir das Problem schon mal wo hatten! Gut, dann würde ich es so auch im Frontend implementieren.

**Comment by pheim1** [comment]
@marlonschlosshauer Wie ist der Stand, machst du es wie beschrieben oder muss das Backend noch etwas daran ändern? Ansonsten bitte closen.

**Comment by marlonschlosshauer** [comment]
Hat sich erledigt, danke für die Erinnerung 👍
