### ISSUE TITLE
Bei fehlerhafter CompanyID werden falsche Projekte zurückgegeben (Default-Return)

### ISSUE THREAD

**Issue by BenjaminKuerten** [gedankenessen/goose-backend#66]
**Beschreibung des Bugs**
Bei fehlerhafter CompanyID werden 3 Projekte als Default zurückgegeben.

**Reproduktions Schritte**
1. Fontend/Swagger
2. Nicht existierende CompanyID eingeben 
3. Ausführen

**Erwartetes Verhalten**
Es sollten keine Projekte zurückkommen

**Branches**
- Frontend: main+Demo
- Backend: master/live

![Screenshot_1](https://user-images.githubusercontent.com/48795982/115903069-706f6c00-a463-11eb-8a88-18fadc7c1721.png)

**Comment by Luk-T** [comment]
Der Fehler ist folgender:

Wenn man in Asp.Net bei einem Controller nicht das ApiControllerAttribut hinzufügt, werden Fehler bei der Validierung des Requests einfach verschluckt, und die Company-Id wurde auf einen default-Wert (00000...) gesetzt. Beim Projektcontroller hab ich das Attribut leider vergessen, sorry
