### ISSUE TITLE
Kann Zusammenfassung nicht ablehnen

### ISSUE THREAD

**Issue by WhiroWhat** [gedankenessen/goose-backend#68]
**Beschreibung des Bugs**
Beim ablehnen einer Zusammenfassung kommt immer:
```js
{"message":"Die Zusammenfassung wurde schon angenommen und kann nicht abgelehnt werden","status":400,"type":"HttpStatusException"}
```

**Reproduktions Schritte**
1.  Zusammenfassung erstellen
2.  Zusammenfassung ablehnen (PUT: http://51.254.157.180:5000/api/issues/60882bdd4f7533d0c74a822f/summaries?accept=false, body: {})

**Branches**
- Frontend: hotfix/ConversationComponentVS2
- Backend: master

**Comment by Madara789** [comment]
so release läuft sollte nun gefixt sein
das Problem war, dass die default werte von RequirementsAccepted und RequirementsSummaryCreated auf true waren

**Comment by pheim1** [comment]
@WhiroWhat Bitte schließen, falls der Bug gefixed wurde.

**Comment by WhiroWhat** [comment]
yep sry
