### ISSUE TITLE
Projekt Dashboard: Filtern der Projekte

### ISSUE THREAD

**Issue by Namo2** [gedankenessen/goose-backend#69]
**Beschreibung des Bugs**
Hey, auf dem ProjektDashboard werden im Moment immer alle Projekte einer Firma angezeigt.
Auch wenn man z.B. als Kunde eingeloggt ist.

**Reproduktions Schritte**
1. Go to '/login'
2. Loginname: 'MRoss' (Passwort schreibe ich in den Discord)
3. Auf Login klicken

**Erwartetes Verhalten**
Auf dem Dashboard sollten nur die Projekte des Kunden aufgelistet werden.

@marlonschlosshauer sollten für Mitarbeiter auch nur die Projekte angezeigt werden, wo diese Rechte haben / beteiligt sind?

**Branches**
- Frontend: main
- Backend: master

**Comment by marlonschlosshauer** [comment]
> @marlonschlosshauer sollten für Mitarbeiter auch nur die Projekte angezeigt werden, wo diese Rechte haben / beteiligt sind?

Yep. Kann sein das wir davon aber in der Tracebility noch nicht angenommene Aufgaben haben.

**Comment by Luk-T** [comment]
Ich kümmer mich drum 👍

**Comment by Luk-T** [comment]
Ich würde das so implementieren:
Der Firmenaccount bekommt alle Projekte der Company, ansonsten (MItarbeiter & Kunden) bekommt man nur die Projekte in denen man auch eine Rolle hat.
Das sollte ja passen, oder?

**Comment by Namo2** [comment]
Würde ich auch so sagen

**Comment by marlonschlosshauer** [comment]
@Luk-T Gab es hierfür nen Fix ?

**Comment by Luk-T** [comment]
Kommt heute noch

**Comment by pheim1** [comment]
@Namo2 Wurde der Bug gefixed? Das Ticket sollte zwar mit #72 automatisch schließen aber naja :D

**Comment by Namo2** [comment]
> @Namo2 Wurde der Bug gefixed? Das Ticket sollte zwar mit #72 automatisch schließen aber naja :D

Jap ist mittlerweile gefixed :+1:
