### ISSUE TITLE
GET Issues wirft 500 statt 401 wenn keine Rechte

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#76]

**Comment by pheim1** [comment]
401 unauthorized- nicht angemeldet, fehlender JWT Token 
403 forbidden - keine Rechte

Welches meinst du ?

**Comment by marlonschlosshauer** [comment]
Sorry mit keine Rechte meinte ich das ich nicht als ProjectUser hinzugefügt war. Hab dann da 500 bekommen statt 403 oder 401.

**Comment by marlonschlosshauer** [comment]
@Yochyo hast du das gefixed oder war das #not-a-bug?

**Comment by Madara789** [comment]
sollte gefixt sein jz mit neusten release! war mein fehler : (
