### ISSUE TITLE
Rolle Firma müsste auch eine Projektrolle sein oder?

### ISSUE THREAD

**Issue by WhiroWhat** [gedankenessen/goose-backend#77]

**Comment by pheim1** [comment]
Kann, aber habe es so, dass ein Firmen-Owner in der Firma und nicht im Projekt diese Rolle hat. Du kannst ja zu dem jeweiligen Projekt die Rolle eines Users in der Company auslesen (companyId).

**Comment by Yochyo** [comment]
Wir hatten einen Bug im Backend bei dem beim erstellen eines Issues nicht geprüft wurde ob der User einer Firma ist.
Ich hatte dazu gesagt, dass der Fix dazu etwas komplizierter ist, da die Firma keine Projektrolle ist (deshalb dieses Issue).

Gerade eben hat mir Willy aber gezeigt, dass das gar kein Problem ist.
