### ISSUE TITLE
Prallele Schreibanfragen an die Datenbank führen zu falschen verhalten.

### ISSUE THREAD

**Issue by Yochyo** [gedankenessen/goose-backend#78]
Gerade eben gab es einen Bug beim gleichzeitigen Hinzufügen von mehreren ProjectUsern. Der Grund dafür war, dass bei beiden Anfragen das Projekt gleichzeitig aus der DB geladen wurde, der ProjektUser hinzugefügt wurde und anschließend geupdated wurde. 

Am Ende stand meistens nur einer der ProjectUsern in der DB.

Das gleiche Problem wird später auftauchen, wenn mehr als ein Nutzer die App verwendet. Wir müssen im Backend also zwingend Transaktionen einführen.

Die wahrscheinlich einfachste Lösung wäre, wenn jeder Service eine Lock (ReaderWriterLock) besitzt.
Eine AsyncReaderWriterLock (Das ist ein Nugget package) bietet sich dafür am meisten an.

**Comment by Yochyo** [comment]
Außerdem funktionierten die Locks nicht, da für jede Anfrage ein neuer Service erstellt wurde (da der Service Scoped (nicht ein Singleton) war).

**Comment by Luk-T** [comment]
> Die wahrscheinlich einfachste Lösung wäre, wenn jeder Service eine Lock (ReaderWriterLock) besitzt.

Das wird nicht alle Probleme beheben. Wenn z.B. der ProjectUserService dem Projekt ein neuen Nutzer erstellt und gleichzeitig über den StateService ein neuer Status angelegt wird kann auch eine Änderung die andere überschreiben, weil beides im selben Dokument in der Datenbank gespeichert wird.

Ich sehe folgende Möglichkeiten:
- Wir kriegen die Transaktionen von mongoDB zum Laufen. Dann würden Konflikte beim Schreiben von Dokumenten erkannt werden und im Fall des Falles würde ein TransientTransactionError bei der zweiten Transaktion geworfen. Mehr dazu: #2 

- Wir ändern alle Schreibzugriffe so ab, das nur die nötigen Felder upgedated werden und nicht mehr das gesamte Dokument ersetzt wird (z.B mit dem $push um ein Element in ein Array hinzuzufügen). Damit würde ein zweites Update nicht mehr das erste überschreiben, aber der Service könnte natürlich die alte Version gelesen haben, was wiederum auch Probleme verursachen könnte

- Bei jedem Request wird eine Liste von Dokumenten verwaltet, die gerade benötigt werden. Wenn ein anderer Request ein Dokument anfordert wird zuerst nachgeschaut ob es gerade bearbeitet wird ist bzw. gewartet bis es frei ist. Würde ich nicht machen, weil der Ansatz zu aufwändig ist und viele eklige Fehler zulässt (Deadlocks usw.)

- Der Server beantwortet nur eine Anfrage gleichzeitig. Ist zwar dumm, aber wäre wahrscheinlich am wenigsten Arbeit

**Comment by pheim1** [comment]
Gute Zusammenfassung @Luk-T. 
Am Anfang des Projektes habe ich den Vorschlag gemacht, ein Dokument mit einer Versions-Property zu versehen, damit wird sicher gestellt, dass man zumindest Optimistische Nebenläufigkeit hat: User 1 ladet die Daten, modifiziert sie, speichert aber noch nicht, User 2 ladet die Daten und speichert seine Änderungen vor User 1. Versucht nun User 1 zu speichern, so schlägt es fehl, da die Version des Dokuments von User 2 um eins inkrementiert wurde und der Abstand zur Datenbank um mehr als 1 vorhanden ist. Das wird denke ich auch für den Rahmen des Projektes am einfachsten/effizientesten sein, was meint ihr dazu @gedankenessen/backend ?

**Comment by Madara789** [comment]
Diese ganze Sache ist ja aufgekommen weil wir im Frontend erstmalig einen ganz speziellen fall.
Und zwar wird es momentan im Frontend so gemacht: 
Es wird ein Projekt erstellt, dazu wir automatisch und vorallem gleichzeitig der Firmen Account und der Kunde dem Projekt hinzugefügt. weshalb wir auch erst darauf gekommen sind, weil nachdem alle Request´s durch waren gab es manchmal nur einen Kunden oder nur den Firmen Account im Projekt, dies sollte ja trotzdem funktionieren.
Ich glaube in diesem Fall macht es dann wenig sinn einen Fehler zu werfen.
Deswegen sollten wir vielleicht gucken ob es nicht doch irgendwie mit Sessions, wie Lukas sie angebracht hat oder mit Mutexen funktioniert.

**Comment by marlonschlosshauer** [comment]
> Versucht nun User 1 zu speichern, so schlägt es fehl

Wie würde das Frontend am besten damit umgehen ? Einen Sleep dazwischen schalten ? Bei dem Fehler eine Retransmission probieren? 

Falls wir bis Donnerstag keine elegante Lösung gefunden haben, würde ich ein Sleep zwischen den zwei PUTs schalten.

**Comment by pheim1** [comment]
> > Versucht nun User 1 zu speichern, so schlägt es fehl
> 
> Wie würde das Frontend am besten damit umgehen ? Einen Sleep dazwischen schalten ? Bei dem Fehler eine Retransmission probieren?

Mit `RxJS` kann man ja Aufrufe verzögern. Alternativ kann man auch `retry` für Retransmission einsetzen. Wobei das eigentlich nicht direkt Aufgabe des Frontends ist, aber eine möglicher Workaround.

>
>Deswegen sollten wir vielleicht gucken ob es nicht doch irgendwie mit Sessions, wie Lukas sie angebracht hat oder mit Mutexen funktioniert.

Sessions fällt ja flach, ohne `replica set` (Außer da findet jemand ne Lösung). Will man ordentliche Fehlerbehebung, muss man halt Zeit und Mühe investieren, wie es bei einem richtigen Projekt angebracht ist (schnelle aber dreckige Lösung -> Versionen in Dokumenten und Frontend nutzt retry).

**Comment by Madara789** [comment]
Wie sieht es dann mit Mutexen aus? 
Wir hatten da gestern halt bisschen ausprobiert und dass hatte dann geklappt sowohl Kunde als auch Firmen Account war jedes mal Korrekt drinnen. 
Dies Löst zwar nicht wirklich das Problem welches Lukas geschildert hat aber so können wir zumindest gleichzeitige zugriffe auf den gleichen Controller Locken.
Ich war mir nur nicht sicher ob die Implementierung wirklich akkurat ist, wie sie jetzt im PR (Hotfix/create_project_user) vorhanden ist, da ich dort die Services nicht mehr mit AddScoped sondern AddSingelton hinzufüge und ich meine, dass es einen Grund gab, dass die mit AddScoped hinzugefügt wurden.
Aber selbst das könnte man eventuell mit static Mutexen lösen.

**Comment by pheim1** [comment]
Ich hab evtl. einen weg gefunden, eine `replica set` zu deployen. Falls morgen alles klappt, können wir dann Session benutzen.

**Comment by pheim1** [comment]
Update: Ich habe so eben ein replica set auf unserem server deployed. Nun muss ich es mal lokal testen und dann müssen wir noch die Connection Strings anpassen. 

@gedankenessen/alle Die Daten sind dann bis auf weiters wieder weg. Falls es wichtig ist, kann ich sie auch auf die neue Datenbank migrieren, dann bitte mich an schreiben.

**Comment by pheim1** [comment]
Also lokal konnte ich eine Session aufbauen und einen Commit schreiben. Ich poste in Discord den neuen Connection String. Den Connection String des live Backends werde ich vor dem PR, welcher die Sessions verwendet umändern.

**Comment by marlonschlosshauer** [comment]
> @gedankenessen/alle Die Daten sind dann bis auf weiters wieder weg. Falls es wichtig ist, kann ich sie auch auf die neue Datenbank migrieren, dann bitte mich an schreiben.

Kill die Daten. Wollte ich heute Abend sowieso anfragen. Würde gerne beim Meeting über den Einfluss auf das Frontend (2x PUT ProjectUser etc.) von der Änderung reden.

**Comment by marlonschlosshauer** [comment]
#80 schließt dieses Issue, oder?
