### ISSUE TITLE
Kunde hat keine Berechtigung Ticket zu sehen

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#81]
**Beschreibung des Bugs**
Kunde kann Tickets eines Projektes in dem er Kunde ist nicht ansehen 

![Screen Shot 2021-05-06 at 10 34 39](https://user-images.githubusercontent.com/24259317/117267815-f5408980-ae56-11eb-9672-3ce4fb01e65e.png)
![Screen Shot 2021-05-06 at 10 35 29](https://user-images.githubusercontent.com/24259317/117267822-f70a4d00-ae56-11eb-98b7-0af4e712ae0e.png)

Ticke in Frage hat Id: ``6093a9b29a7ee12d76cd276e``, Kunde: ``6093a6b79a7ee12d76cd275c``, Projekt: ``6093a70e9a7ee12d76cd275f``

**Reproduktions Schritte**
1. Ticket als Firma erstellen
2. Ticket als Kunde auffmachen

**Branches**
- Frontend: demo_Plenarsitzung
- Backend: master

**Comment by Yochyo** [comment]
Sollte gefixt sein, bitte ausprobieren.

**Comment by marlonschlosshauer** [comment]
Ist gefixed, danke 👍
