### ISSUE TITLE
Mitarbeiter kann sich nicht einlogen (Cannot signIn)

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#82]
**Beschreibung des Bugs**
Wollte mich mit Mitarbeiter (CWetzel) einloggen. Kunde & Firma hat funktioniert. 

Fehlermeldung:
![Screen Shot 2021-05-06 at 10 44 39](https://user-images.githubusercontent.com/24259317/117269840-ebb82100-ae58-11eb-9772-f10bdfa0ed4b.png)

Erstellen von CompanyUser gibt 200:
![Screen Shot 2021-05-06 at 10 49 37](https://user-images.githubusercontent.com/24259317/117269962-068a9580-ae59-11eb-87ca-13b0016e5724.png)

Mitarbeiter wird auch unter "CompanyUser" zurückgegeben:

![image](https://user-images.githubusercontent.com/24259317/117270200-42255f80-ae59-11eb-8d49-41e67f656810.png)

CompanyID: ``6093a5449a7ee12d76cd275b``
UserId: ``6093ad929a7ee12d76cd276f``

Es gibt in der Company ein Projekt auf dem der Benutzer (noch) keine Rechte hat. In dem Projekt gibt es zwei Tickets dennen er noch nicht zugeteilt ist. Aber weder noch sollten das verursachen.

**Reproduktions Schritte**
1. Erstelle Mitarbeiter
2. (Öffne Inkognito Browser)
3. Login als Mitarbeiter

**Branches**
- Frontend: demo_Plenarsitzung
- Backend: master

**Comment by pheim1** [comment]
Eventuell vertippt ?
![image](https://user-images.githubusercontent.com/58334704/117271014-1656a980-ae5a-11eb-82d3-85dee640d9cf.png)

**Comment by pheim1** [comment]
Also als `OLeztew` mit `qweqweqweqwe1` kann ich mich anmelden. Kannst du mir noch das PW für `CWetzel` geben?

**Comment by marlonschlosshauer** [comment]
Hab das PW falsch gesetzt... alter. Sorry 😅
