### ISSUE TITLE
Startdatum & Deadline können nicht mit PUT hinzugefügt werden

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#84]
Request schickt Daten mit:
![image](https://user-images.githubusercontent.com/24259317/117282458-1019fa80-ae65-11eb-8928-3afb75097341.png)

**Reproduktions Schritte**
1. Erstelle Ticket ohne Startdatum oder Deadline (oder ohne beides)
2. Bearbeite Ticket und füge entweder oder ein.
3. Datum wurde nicht übernommen

**Branches**
- Frontend: demo_Plenarsitzung
- Backend: master

**Comment by Yochyo** [comment]
Momentan können Start/End-Daten nur in der Verhandlungsphase verändert werden. Im Pflichtenheft steht, dass nur das End-Datum immer geändert werden kann.
Soll beides immer Veränderbar sein?

**Comment by marlonschlosshauer** [comment]
Guter Catch! Würde ich dann so lassen. Wenn sowieso ein Check drin ist (und es nicht zu viel arbeit wäre) würde ich vielleicht eine Fehlermeldung zurückschicken (somit auch die Anfrage rejecten).
