### ISSUE TITLE
Zeiterfassung: Erweiterung + Logik

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-backend#86]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T17 Mitarbeiter kann (für jedes Ticket) Zeiterfassen starten
- [x] T18 Mitarbeiter kann Zeiterfassen stoppen
- [x] T19 Mitarbeiter kann nur eigene Zeiterfassungen stoppen
- [x] T20 Nur Mitarbeiter und Firma können Zeiterfassungen sehen
- [x] T21 Mitarbeiter kann nur eine Zeiterfassung aktiv haben
- [x] T22 Alte Zeiterfassung wird gestoppt beim start von neuer gestoppt
- [x] T41 Nur Nutzer mit "Schreiberecht" darf Zeiten auf Ticket buchen
- [x] T46 Erfasste Zeiten können bearbeitet werden
- [x] T47 Erfasste Zeiten können nur von Mitarbeiter selbst, Projektleiter und Firma bearbeitet werden

**Comment by Luk-T** [comment]
Einige Sachen von dem TIcket waren bereits erledigt. Ich in der Traceability map wie folgt zugeordnet:

T17, T18: Schon implementiert von @Yochyo 
T19, T41, T46, T47: Schon implementiert von @pheim1 

Ich hoffe das ist so korrekt

**Comment by marlonschlosshauer** [comment]
Mehr als korrekt, danke 👍
