### ISSUE TITLE
Issue Ober-/Unterticket Logik

### ISSUE THREAD

**Issue by Yochyo** [gedankenessen/goose-backend#92]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T87 Ein Ticket kann Untertickets beinhalten
- [x] T90 Ein Unterticket blockiert wenn es die Bearbeitungsphase erreicht aber das Oberticket noch Verhandelt
- [x] T91 Ein Unterticket kann nicht während Review oder Abschlussphase hinzugefügt werden
- [x] T93 Ein Unterticket hat genau ein Oberticket

**Comment by marlonschlosshauer** [comment]
Hab T88, T89, T92 in #100 ausgelagert.

**Comment by Yochyo** [comment]
👍
