### ISSUE TITLE
403 beim Hinzufügen eines Custom States

### ISSUE THREAD

**Issue by Namo2** [gedankenessen/goose-backend#97]
**Beschreibung des Bugs**
Hey, ich bekomme den Folgenden Error wenn ich versuche einen Eigenen Status zu einem Projekt hinzuzufügen (Als Firmen Account).
Ich denke es liegt daran, dass der Firmen Account hierbei nicht soviele Rechte hat wie ein Projektleiter.
Error:
```json
{
  "message": "You missing the employee role in this project, in order to create a state.\nYou missing the leader role in this project, in order to create a state.\n",
  "status": 403,
  "type": "HttpStatusException",
  "stackTrace": ""
}
```

**Input Values**
CompanyId: 609421f4d837b069802b738e
ProjectId: 609a569e62225c02480e1c20
Json: 
```json
{
  "name":"Custom State 1",
  "phase":"Bearbeitungsphase",
  "userGenerated":true
}

```

**Reproduktions Schritte**
1. Go to Swagger
2. Einloggen als MSchlosshauer
3. POST bei State (Siehe eingabe Daten oben).

**Erwartetes Verhalten**
Der Status sollte auch mit dem Firmen Account richtig angelegt werden

**Branches**
- Frontend: main
- Backend: master

**Comment by Madara789** [comment]
Hab mal einen Release gemacht bitte noch mal Prüfen 
Company sollte nun einen State erstellen können

**Comment by Namo2** [comment]
Jetzt funktioniert wieder alles :+1:
